// Curated NHL journeymen (active or recently retired) who have played for at
// least 3 distinct NHL franchises. Team names match the CURRENT franchise
// display name in packages/data/src/playerdle/nhl/teams.json (so color lookups
// resolve even when a stint predates a rebrand: Phoenix/Arizona → Utah Mammoth,
// Atlanta Thrashers → Winnipeg Jets).
//
// Generated by scripts/sync-journey-players-nhl.ts. Run `pnpm sync:journey:nhl`
// to refresh team lists from the official NHL API (api-web.nhle.com). Edit
// the players' id/name/position by hand; the script will preserve those fields
// and overwrite the teams[] array with the API-derived history.

import type { JourneyPlayer } from "./players"

export const NHL_JOURNEY_PLAYERS: JourneyPlayer[] = [
  {
    id: "journey:nhl:phil-kessel",
    name: "Phil Kessel",
    position: "RW",
    teams: [
      "Boston Bruins",
      "Toronto Maple Leafs",
      "Pittsburgh Penguins",
      "Utah Mammoth",
      "Vegas Golden Knights",
    ],
  },
  {
    id: "journey:nhl:patrick-marleau",
    name: "Patrick Marleau",
    position: "C",
    teams: ["San Jose Sharks", "Toronto Maple Leafs", "San Jose Sharks", "Pittsburgh Penguins"],
  },
  {
    id: "journey:nhl:joe-thornton",
    name: "Joe Thornton",
    position: "C",
    teams: ["Boston Bruins", "San Jose Sharks", "Toronto Maple Leafs", "Florida Panthers"],
  },
  {
    id: "journey:nhl:tyler-toffoli",
    name: "Tyler Toffoli",
    position: "RW",
    teams: [
      "Los Angeles Kings",
      "Vancouver Canucks",
      "Montreal Canadiens",
      "Calgary Flames",
      "New Jersey Devils",
      "Winnipeg Jets",
      "San Jose Sharks",
    ],
  },
  {
    id: "journey:nhl:pk-subban",
    name: "P.K. Subban",
    position: "D",
    teams: ["Montreal Canadiens", "Nashville Predators", "New Jersey Devils"],
  },
  {
    id: "journey:nhl:mike-hoffman",
    name: "Mike Hoffman",
    position: "LW",
    teams: [
      "Ottawa Senators",
      "San Jose Sharks",
      "Florida Panthers",
      "St. Louis Blues",
      "Montreal Canadiens",
      "Anaheim Ducks",
    ],
  },
  {
    id: "journey:nhl:erik-karlsson",
    name: "Erik Karlsson",
    position: "D",
    teams: ["Ottawa Senators", "San Jose Sharks", "Pittsburgh Penguins"],
  },
  {
    id: "journey:nhl:james-neal",
    name: "James Neal",
    position: "LW",
    teams: [
      "Dallas Stars",
      "Pittsburgh Penguins",
      "Nashville Predators",
      "Vegas Golden Knights",
      "Calgary Flames",
      "Edmonton Oilers",
      "St. Louis Blues",
    ],
  },
  {
    id: "journey:nhl:john-klingberg",
    name: "John Klingberg",
    position: "D",
    teams: [
      "Dallas Stars",
      "Anaheim Ducks",
      "Minnesota Wild",
      "Toronto Maple Leafs",
      "New York Rangers",
    ],
  },
  {
    id: "journey:nhl:mike-smith",
    name: "Mike Smith",
    position: "G",
    teams: [
      "Dallas Stars",
      "Tampa Bay Lightning",
      "Utah Mammoth",
      "Calgary Flames",
      "Edmonton Oilers",
    ],
  },
  {
    id: "journey:nhl:marc-andre-fleury",
    name: "Marc-Andre Fleury",
    position: "G",
    teams: ["Pittsburgh Penguins", "Vegas Golden Knights", "Chicago Blackhawks", "Minnesota Wild"],
  },
  {
    id: "journey:nhl:bobby-ryan",
    name: "Bobby Ryan",
    position: "RW",
    teams: ["Anaheim Ducks", "Ottawa Senators", "Detroit Red Wings"],
  },
  {
    id: "journey:nhl:patric-hornqvist",
    name: "Patric Hornqvist",
    position: "RW",
    teams: ["Nashville Predators", "Pittsburgh Penguins", "Florida Panthers"],
  },
  {
    id: "journey:nhl:andreas-athanasiou",
    name: "Andreas Athanasiou",
    position: "C",
    teams: ["Detroit Red Wings", "Edmonton Oilers", "Los Angeles Kings", "Chicago Blackhawks"],
  },
  {
    id: "journey:nhl:eric-staal",
    name: "Eric Staal",
    position: "C",
    teams: [
      "Carolina Hurricanes",
      "New York Rangers",
      "Minnesota Wild",
      "Buffalo Sabres",
      "Montreal Canadiens",
      "Florida Panthers",
    ],
  },
  {
    id: "journey:nhl:jason-spezza",
    name: "Jason Spezza",
    position: "C",
    teams: ["Ottawa Senators", "Dallas Stars", "Toronto Maple Leafs"],
  },
  {
    id: "journey:nhl:loui-eriksson",
    name: "Loui Eriksson",
    position: "LW",
    teams: [
      "Dallas Stars",
      "Boston Bruins",
      "Vancouver Canucks",
      "Utah Mammoth",
      "Vegas Golden Knights",
    ],
  },
  {
    id: "journey:nhl:andrew-ladd",
    name: "Andrew Ladd",
    position: "LW",
    teams: [
      "Carolina Hurricanes",
      "Chicago Blackhawks",
      "Winnipeg Jets",
      "Chicago Blackhawks",
      "Winnipeg Jets",
      "New York Islanders",
      "Utah Mammoth",
    ],
  },
  {
    id: "journey:nhl:tomas-tatar",
    name: "Tomas Tatar",
    position: "LW",
    teams: [
      "Detroit Red Wings",
      "Vegas Golden Knights",
      "Montreal Canadiens",
      "New Jersey Devils",
      "Colorado Avalanche",
      "Seattle Kraken",
    ],
  },
  {
    id: "journey:nhl:cody-eakin",
    name: "Cody Eakin",
    position: "C",
    teams: [
      "Washington Capitals",
      "Dallas Stars",
      "Vegas Golden Knights",
      "Winnipeg Jets",
      "Buffalo Sabres",
      "Montreal Canadiens",
    ],
  },
  {
    id: "journey:nhl:erik-gudbranson",
    name: "Erik Gudbranson",
    position: "D",
    teams: [
      "Florida Panthers",
      "Vancouver Canucks",
      "Pittsburgh Penguins",
      "Anaheim Ducks",
      "Nashville Predators",
      "Ottawa Senators",
      "Columbus Blue Jackets",
    ],
  },
  {
    id: "journey:nhl:vincent-trocheck",
    name: "Vincent Trocheck",
    position: "C",
    teams: ["Florida Panthers", "Carolina Hurricanes", "New York Rangers"],
  },
  {
    id: "journey:nhl:tyler-bertuzzi",
    name: "Tyler Bertuzzi",
    position: "LW",
    teams: ["Detroit Red Wings", "Boston Bruins", "Toronto Maple Leafs", "Chicago Blackhawks"],
  },
  {
    id: "journey:nhl:vladimir-tarasenko",
    name: "Vladimir Tarasenko",
    position: "RW",
    teams: [
      "St. Louis Blues",
      "New York Rangers",
      "Ottawa Senators",
      "Florida Panthers",
      "Detroit Red Wings",
    ],
  },
  {
    id: "journey:nhl:ryan-oreilly",
    name: "Ryan O'Reilly",
    position: "C",
    teams: [
      "Colorado Avalanche",
      "Buffalo Sabres",
      "St. Louis Blues",
      "Toronto Maple Leafs",
      "Nashville Predators",
    ],
  },
]

export const NHL_ELIGIBLE_POSITIONS: ReadonlyArray<string> = ["C", "LW", "RW", "D", "G"]
