export const WORDLIST: string[] = [
  "aardvark", "albatross", "alligator", "alpaca", "anaconda",
  "anchovy", "antelope", "anteater", "armadillo", "asp",
  "axolotl", "baboon", "badger", "barnacle", "barracuda",
  "bat", "bear", "beaver", "bison", "blackbird",
  "bluebird", "boa", "boar", "bobcat", "bream",
  "budgie", "buffalo", "bull", "bullfrog", "burro",
  "butterfly", "camel", "canary", "capybara", "caracal",
  "cardinal", "caribou", "cassowary", "catfish", "centipede",
  "chameleon", "cheetah", "chimpanzee", "chipmunk", "clam",
  "clownfish", "cobra", "condor", "cormorant", "cougar",
  "coyote", "crab", "crane", "cricket", "crocodile",
  "crow", "cuckoo", "curlew", "dace", "darter",
  "deer", "dingo", "dodo", "dolphin", "donkey",
  "dormouse", "dove", "dragonfly", "duck", "dunlin",
  "eagle", "egret", "elephant", "elk", "emu",
  "falcon", "ferret", "finch", "firefly", "flamingo",
  "flounder", "fox", "frog", "fulmar", "gannet",
  "gazelle", "gecko", "genet", "gerbil", "gibbon",
  "giraffe", "goat", "goose", "gopher", "gorilla",
  "grasshopper", "grizzly", "groundhog", "grouse", "guillemot",
  "guppy", "halibut", "hamster", "hare", "harrier",
  "hawk", "hedgehog", "heron", "herring", "hippo",
  "honeybee", "hoopoe", "hornbill", "horse", "hummingbird",
  "hyena", "ibis", "iguana", "impala", "jackal",
  "jackdaw", "jaguar", "jay", "jellyfish", "kangaroo",
  "kingfisher", "kite", "kiwi", "koala", "komodo",
  "kudu", "lapwing", "lemur", "leopard", "lion",
  "lizard", "llama", "lobster", "locust", "loon",
  "lynx", "macaw", "magpie", "mallard", "manatee",
  "mandrill", "marlin", "marmot", "meerkat", "millipede",
  "mink", "mole", "mongoose", "moose", "mudskipper",
  "muskrat", "mussel", "narwhal", "newt", "nightjar",
  "numbat", "ocelot", "octopus", "okapi", "opossum",
  "orca", "oriole", "oryx", "osprey", "otter",
  "owl", "panda", "panther", "parakeet", "parrot",
  "peacock", "peccary", "pelican", "penguin", "perch",
  "pheasant", "pigeon", "pike", "piranha", "platypus",
  "plover", "pony", "porcupine", "porpoise", "prawn",
  "pronghorn", "puffin", "quail", "quetzal", "rabbit",
  "raccoon", "raven", "reindeer", "roadrunner", "robin",
  "sable", "salamander", "sandpiper", "sardine", "seal",
  "seahorse", "shark", "shrew", "shrimp", "sidewinder",
  "skunk", "sloth", "snail", "snipe", "sparrow",
  "squid", "squirrel", "starfish", "starling", "stoat",
  "stork", "sturgeon", "sunfish", "swan", "swift",
  "tapir", "tarantula", "termite", "tern", "thrush",
  "tiger", "toad", "tortoise", "toucan", "trout",
  "tuna", "turkey", "turtle", "viper", "vole",
  "wallaby", "warbler", "weasel", "wildcat", "wolverine",
  "wombat", "woodpecker", "wren", "yak", "zebra",
]

if (WORDLIST.length !== 250) {
  throw new Error(`WORDLIST must have 250 entries (found ${WORDLIST.length})`)
}
