export const WORDLIST: string[] = [
  "albatross", "alligator", "alpaca", "antelope", "armadillo",
  "axolotl", "badger", "barracuda", "bat", "bear",
  "beaver", "bison", "bobcat", "buffalo", "bullfrog",
  "butterfly", "capybara", "cassowary", "cheetah", "chipmunk",
  "cobra", "condor", "coyote", "crane", "cricket",
  "crocodile", "crow", "deer", "dingo", "dolphin",
  "donkey", "dove", "dragonfly", "duck", "eagle",
  "egret", "elephant", "elk", "emu", "falcon",
  "ferret", "flamingo", "fox", "frog", "gecko",
  "giraffe", "goat", "goose", "gorilla", "grizzly",
  "groundhog", "grouse", "hamster", "hare", "hawk",
  "hedgehog", "heron", "hippo", "hornbill", "horse",
  "hummingbird", "hyena", "iguana", "jackal", "jaguar",
  "jay", "jellyfish", "kangaroo", "kingfisher", "kiwi",
  "koala", "komodo", "leopard", "lion", "lizard",
  "llama", "lobster", "loon", "lynx", "macaw",
  "manatee", "marmot", "mink", "mongoose", "moose",
  "narwhal", "newt", "ocelot", "octopus", "opossum",
  "orca", "osprey", "otter", "owl", "panda",
  "panther", "parrot", "peacock", "pelican", "penguin",
  "pheasant", "platypus", "porcupine", "puffin", "quail",
  "rabbit", "raccoon", "raven", "robin", "salamander",
  "seal", "shark", "skunk", "sloth", "snail",
  "sparrow", "squid", "squirrel", "stork", "swan",
  "tarantula", "tiger", "toad", "tortoise", "toucan",
]
