export const WORDLIST: string[] = [
  "aardvark", "agouti", "albatross", "alligator", "alpaca",
  "anaconda", "anchovy", "ant", "antelope", "ape",
  "armadillo", "asp", "axolotl", "baboon", "badger",
  "barnacle", "barracuda", "bass", "bat", "bear",
  "beaver", "bee", "beetle", "bison", "boa",
  "boar", "bobcat", "bream", "budgie", "buffalo",
  "bull", "burro", "caiman", "camel", "canary",
  "capybara", "caracal", "cardinal", "caribou", "cassowary",
  "centipede", "chameleon", "cheetah", "chimpanzee", "chipmunk",
  "chub", "clam", "coati", "cobra", "condor",
  "cormorant", "cougar", "coyote", "crab", "crane",
  "cricket", "crocodile", "crow", "cuckoo", "curlew",
  "dace", "darter", "deer", "dingo", "dodo",
  "dolphin", "donkey", "dove", "duck", "dunlin",
  "eagle", "echidna", "egret", "elephant", "elk",
  "emu", "ermine", "falcon", "ferret", "finch",
  "flamingo", "flounder", "fly", "fox", "frog",
  "fulmar", "gannet", "gazelle", "gecko", "genet",
  "gerbil", "gibbon", "giraffe", "gnu", "goat",
  "goose", "gopher", "gorilla", "grizzly", "grouse",
  "guanaco", "guillemot", "guppy", "haddock", "hake",
  "halibut", "hamster", "hare", "harrier", "hawk",
  "hen", "heron", "herring", "hippo", "hoopoe",
  "horse", "hyena", "ibex", "ibis", "iguana",
  "impala", "jackal", "jaguar", "jay", "kangaroo",
  "kestrel", "kite", "kiwi", "koala", "komodo",
  "kudu", "lamprey", "lapwing", "lemur", "leopard",
  "linnet", "lion", "lizard", "llama", "lobster",
  "locust", "loon", "loris", "lynx", "macaque",
  "macaw", "magpie", "mallard", "manatee", "mandrill",
  "mantis", "marlin", "marmot", "meerkat", "millipede",
  "mink", "minnow", "mole", "mongoose", "moose",
  "moth", "mouse", "mussel", "narwhal", "newt",
  "numbat", "nutria", "ocelot", "octopus", "okapi",
  "opossum", "orca", "oriole", "oryx", "osprey",
  "otter", "owl", "panda", "pangolin", "panther",
  "parakeet", "parrot", "partridge", "peacock", "peccary",
  "pelican", "penguin", "perch", "pheasant", "pigeon",
  "pike", "piranha", "platypus", "plover", "pony",
  "porcupine", "porpoise", "prawn", "puffin", "python",
  "quail", "quetzal", "rabbit", "raccoon", "raven",
  "reindeer", "robin", "sable", "salamander", "sardine",
  "seal", "shark", "shrew", "shrimp", "skunk",
  "sloth", "snail", "snipe", "sparrow", "squid",
  "squirrel", "starling", "stoat", "stork", "sturgeon",
  "swan", "swift", "tapir", "tarantula", "termite",
  "tern", "thrush", "tiger", "toad", "tortoise",
  "toucan", "trout", "tuna", "turkey", "turtle",
  "viper", "vole", "wallaby", "warbler", "weasel",
  "wolverine", "wombat", "wren", "yak", "zebra",
]

if (WORDLIST.length !== 250) {
  throw new Error(`WORDLIST must have 250 entries (found ${WORDLIST.length})`)
}
